export const allProducts = [
  {
    id: '1',
    name: 'Aquafina',
    image: '/images/aqua.jpg',
    description: '',
    brand: '',
    category: 'Beverage',
    price: 10000,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: '2',
    name: 'Cà phê sữa',
    image: '/images/cafe.jpg',
    description: '',
    brand: '',
    category: 'Beverage',
    price: 10000,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    id: '3',
    name: 'Coca Cola',
    image: '/images/coca.jpg',
    description: '',
    brand: '',
    category: 'Beverage',
    price: 10000,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    id: '4',
    name: 'Dasani',
    image: '/images/dasani.jpg',
    description: '',
    brand: '',
    category: 'Beverage',
    price: 10000,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    id: '5',
    name: 'Fanta',
    image: '/images/fanta.jpg',
    description: '',
    brand: '',
    category: 'Beverage',
    price: 10000,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    id: '6',
    name: 'Lipton',
    image: '/images/lipton.jpg',
    description: '',
    brand: 'Amazon',
    category: 'Beverage',
    price: 10000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    id: '7',
    name: 'Mirinda',
    image: '/images/mirinda.jpg',
    description: '',
    brand: 'Amazon',
    category: 'Beverage',
    price: 10000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    id: '8',
    name: 'Pepsi',
    image: '/images/pepsi.jpg',
    description: '',
    brand: '',
    category: 'Beverage',
    price: 10000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
  {
    id: '9',
    name: 'Sprite',
    image: '/images/sprite.jpg',
    description: '',
    brand: '',
    category: 'Beverage',
    price: 10000,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
];
